name: influfinder_flutter
description: "Influfinder - Connect creators with brands"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  shared_preferences: ^2.3.4
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
